<?php /* Smarty version 2.6.19, created on 2008-06-03 14:25:11
         compiled from Home/workspace.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'date_format', 'Home/workspace.tpl', 31, false),array('block', 'dynamic', 'Home/workspace.tpl', 32, false),)), $this); ?>
<?php $this->_cache_serials['/p1/hosting/tweeem/libs/application/smarty/templates_c//%%58^58C^58C9F06E%%workspace.tpl.inc'] = 'c35efb7ef8e4d047e9898cf9df558902'; ?><?php echo '<!-- home/workspace --><script language="JavaScript" type="text/javascript">T.User = '; ?><?php echo '{}'; ?><?php echo ';T.User.login = \''; ?><?php echo $this->_tpl_vars['user']['login']; ?><?php echo '\';T.User.profile_image = '; ?><?php echo '{'; ?><?php echo 'normal: \''; ?><?php echo $this->_tpl_vars['user']['profile_image']['normal']; ?><?php echo '\', mini: \''; ?><?php echo $this->_tpl_vars['user']['profile_image']['mini']; ?><?php echo '\''; ?><?php echo '}'; ?><?php echo ';</script><div id="chatPanel" class="panel" style="visibility: hidden;"><div class="hd"><span>Chat</span><div class="container-minimize"></div></div><div class="bd">'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "Home/workspace/chat.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</div><div class="ft"><span></span></div></div><div id="listPanel" class="panel" style="visibility: hidden;"><div class="hd"><span>List</span><div class="container-minimize"></div></div><div class="bd">'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "Home/workspace/list.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<!--<span>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Suspendisse nulla. Fusce mauris massa, rutrum eu, imperdiet ut, placerat at, nunc. Vestibulum consequat ligula ut lacus. Nulla nec pede. Fusce consequat, augue et eleifend ornare, nibh mi dapibus lorem, ut lacinia turpis eros at eros. Proin laoreet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla velit. Fusce id sem sit amet felis porta mollis. Aliquam erat volutpat. Etiam tortor. Donec dui felis, pretium quis, vulputate et, molestie non, nisi.</span>--></div><div class="ft"><span></span></div></div><div id="minimizedContainer"></div><!-- Cache time: '; ?><?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y-%m-%d %H:%M:%S") : smarty_modifier_date_format($_tmp, "%Y-%m-%d %H:%M:%S")); ?><?php echo ' --><!-- Dynamic time: '; ?><?php if ($this->caching && !$this->_cache_including): echo '{nocache:c35efb7ef8e4d047e9898cf9df558902#0}'; endif;$this->_tag_stack[] = array('dynamic', array()); $_block_repeat=true;smarty_block_dynamic($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo ''; ?><?php echo ((is_array($_tmp=time())) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y-%m-%d %H:%M:%S") : smarty_modifier_date_format($_tmp, "%Y-%m-%d %H:%M:%S")); ?><?php echo ''; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_dynamic($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); if ($this->caching && !$this->_cache_including): echo '{/nocache:c35efb7ef8e4d047e9898cf9df558902#0}'; endif;?><?php echo ' --><!-- /home/workspace -->'; ?>